=== perryhau/EasyExcel4j/src/test/resources/xmlmapper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.w3school.com.cn"  
elementFormDefault="qualified">
  <xs:element name="xmlmapper">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="mapper"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mapper">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="column"/>
      </xs:sequence>
      <xs:attribute name="class" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="column">
    <xs:complexType>
      <xs:attribute name="columnName" use="required" type="xs:NCName"/>
      <xs:attribute name="columnNum" use="required" type="xs:integer"/>
      <xs:attribute name="fieldName" use="required" type="xs:NCName"/>
      <xs:attribute name="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== perryhau/EasyExcel4j/src/test/resources/xmltest1.xml
<?xml version="1.0"?>
<xmlmapper
xmlns="http://www.w3school.com.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn xmlmapper.xsd">
	<mapper class="com.taobao.common.easyExcel4j.EeUser">
		<column columnName="姓名" fieldName="userName"/>
		<column columnName="性别" fieldName="gender"/>
		<column columnName="年龄" fieldName="age"/>
		<column columnName="手机" fieldName="phone"/>
		<column columnName="出生日期" fieldName="birth"/>
		<column columnName="工资" fieldName="salary"/>
	</mapper>
</xmlmapper>
